import { useState, useEffect, useRef } from 'react'
import { useParams, Link } from 'react-router-dom'
import axios from 'axios'
import toast from 'react-hot-toast'
import FactureDocument from '../components/FactureDocument'
import { downloadDocumentPdf } from '../utils/downloadDocumentPdf'
import { buildDisplayRows } from '../utils/factureDisplayRows'
import { useAuth } from '../context/AuthContext'

const fmt = (n) => new Intl.NumberFormat('fr-FR').format(n ?? 0)

/**
 * Facture publique (lien partageable) — même template A4 que FactureView.
 * Téléchargement PDF réservé au personnel (`can_download_document`).
 */
export default function PublicFactureView() {
  const { reference } = useParams()
  const { user } = useAuth()
  const documentRef = useRef(null)
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [errorCode, setErrorCode] = useState(null)
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [pdfLoading, setPdfLoading] = useState(false)

  const isEtudiant = user?.role === 'etudiant'

  useEffect(() => {
    if (isEtudiant) {
      setLoading(false)
      setData(null)
      setError(null)
      return
    }
    setLoading(true)
    setError(null)
    setErrorCode(null)
    axios
      .get(`/api/public/facture-proforma/${reference}`)
      .then(({ data: d }) => {
        setData(d)
        if (d?.auto_generated) setAutoGenerated(true)
      })
      .catch((err) => {
        setError(err.response?.data?.message || 'Facture introuvable')
        setErrorCode(err.response?.data?.code || null)
      })
      .finally(() => setLoading(false))
  }, [reference, isEtudiant])

  const handleDownloadPDF = async () => {
    const el = documentRef.current
    if (!el || !data?.facture || !data?.can_download_document) return
    setPdfLoading(true)
    try {
      await downloadDocumentPdf(el, `${data.facture.numero || reference || 'facture'}.pdf`)
      toast.success('PDF téléchargé.')
    } catch {
      toast.error('Impossible de générer le PDF.')
    } finally {
      setPdfLoading(false)
    }
  }

  if (isEtudiant) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-100 px-4">
        <div className="w-full max-w-md rounded-2xl bg-white p-10 text-center shadow-xl">
          <p className="mb-2 text-sm font-bold uppercase tracking-wide text-red-600">403</p>
          <h2 className="mb-2 text-xl font-bold text-gray-800">Accès refusé</h2>
          <p className="mb-6 text-gray-500">
            Le téléchargement et la consultation du document de facture sont réservés au personnel de l&apos;établissement.
          </p>
          <Link
            to="/dashboard"
            className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-6 py-2.5 font-semibold text-white hover:bg-blue-800"
          >
            Retour à mon espace
          </Link>
        </div>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-100">
        <div className="text-center">
          <div className="mx-auto mb-4 h-14 w-14 animate-spin rounded-full border-4 border-blue-700 border-t-transparent" />
          <p className="font-medium text-gray-600">Chargement de la facture…</p>
        </div>
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-100">
        <div className="w-full max-w-md rounded-2xl bg-white p-10 text-center shadow-xl">
          <h2 className="mb-2 text-xl font-bold text-gray-800">Facture introuvable</h2>
          <p className="mb-6 text-gray-500">{error}</p>
          {errorCode === 'PROFORMA_NOT_VALIDATED' && (
            <div className="mb-6 flex flex-col justify-center gap-2 sm:flex-row">
              <Link to="/login" className="text-sm font-semibold text-blue-700 hover:underline">
                Se connecter
              </Link>
              <Link to="/dashboard" className="text-sm font-semibold text-blue-700 hover:underline">
                Espace étudiant
              </Link>
            </div>
          )}
          <Link
            to="/"
            className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-6 py-2.5 font-semibold text-white hover:bg-blue-800"
          >
            ← Retour à l&apos;accueil
          </Link>
        </div>
      </div>
    )
  }

  const {
    facture,
    prenom,
    nom,
    email,
    telephone,
    type_formation,
    formation_titre,
    type_payeur,
    payeur,
    etablissement_snapshot: es,
  } = data

  const canDownload = data.can_download_document === true
  const etab = es || {}
  const primary = etab.couleur_primaire || '#1e40af'

  // Anonyme / non-staff : résumé statut uniquement, pas de PDF ni document complet
  if (!canDownload) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-100 px-4 py-8">
        <div className="w-full max-w-lg rounded-2xl bg-white p-8 shadow-xl">
          <p className="text-xs font-bold uppercase tracking-wide text-slate-500">Facture proforma</p>
          <h2 className="mt-1 font-mono text-xl font-bold text-slate-900">
            {facture?.numero || reference}
          </h2>
          {facture?.montant_ttc != null && (
            <p className="mt-2 text-2xl font-black tabular-nums text-slate-900">
              {fmt(facture.montant_ttc)} <span className="text-sm font-semibold text-slate-500">FCFA</span>
            </p>
          )}
          {(formation_titre || facture?.formation_snapshot?.titre) && (
            <p className="mt-3 text-sm font-semibold text-slate-800">
              {formation_titre || facture?.formation_snapshot?.titre}
            </p>
          )}
          {(prenom || nom) && (
            <p className="mt-1 text-sm text-slate-600">
              {prenom} {nom}
            </p>
          )}
          <div className="mt-6 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-950">
            Téléchargement réservé au personnel.
          </div>
          <div className="mt-6 text-center">
            <Link
              to="/"
              className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"
            >
              ← Retour à l&apos;accueil
            </Link>
          </div>
        </div>
      </div>
    )
  }

  const fo = {
    titre: formation_titre || facture?.formation_snapshot?.titre,
    niveau: data.niveau || facture?.formation_snapshot?.niveau,
    niveau_requis: facture?.formation_snapshot?.niveau_requis,
    nombre_annees: facture?.formation_snapshot?.nombre_annees,
    type: type_formation || facture?.formation_snapshot?.type,
    duree: data.formation_duree || facture?.formation_snapshot?.duree,
    duree_formation: data.formation_duree,
    duree_mois: facture?.formation_snapshot?.duree_mois,
    mensualite: facture?.formation_snapshot?.mensualite,
    frais_inscription: facture?.formation_snapshot?.frais_inscription,
    frais_bibliotheque: facture?.formation_snapshot?.frais_bibliotheque,
    frais_epi: facture?.formation_snapshot?.frais_epi,
    libelles_champs: facture?.formation_snapshot?.libelles_champs,
    description: data.formation_description || facture?.formation_snapshot?.description || '',
    debouches: facture?.formation_snapshot?.debouches || '',
  }
  const { rows, totalAPayer } = buildDisplayRows(
    {
      ...facture,
      type_payeur: type_payeur || facture?.type_payeur,
      payeur: payeur || facture?.payeur,
    },
    { ...fo, ...facture?.formation_snapshot },
  )

  return (
    <div className="lettre-print-scope min-h-screen bg-slate-100 px-4 py-8">
      <div className="no-print mx-auto mb-5 flex max-w-[210mm] flex-wrap items-center justify-between gap-3">
        <Link
          to="/"
          className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
        >
          ← Retour à l&apos;accueil
        </Link>
        <div className="flex items-center gap-3">
          {autoGenerated && (
            <span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-800">
              PDF généré automatiquement
            </span>
          )}
          <button
            type="button"
            onClick={handleDownloadPDF}
            disabled={pdfLoading}
            className="rounded-lg px-5 py-2.5 text-sm font-bold text-white shadow-md disabled:opacity-60"
            style={{ backgroundColor: primary }}
          >
            {pdfLoading ? 'Préparation…' : 'Télécharger le PDF'}
          </button>
        </div>
      </div>

      <div className="a4-preview-stage">
        <FactureDocument
          documentRef={documentRef}
          etab={etab}
          facture={{
            ...facture,
            type_payeur: type_payeur || facture?.type_payeur,
            payeur: payeur || facture?.payeur,
            date_emission: facture?.date_emission || data.created_at,
            annee_academique: facture?.annee_academique || data.annee_academique,
          }}
          etudiant={{ prenom, nom, email, telephone }}
          formation={{
            ...fo,
            description: fo.description || facture?.formation_snapshot?.description || '',
            debouches: fo.debouches || facture?.formation_snapshot?.debouches || '',
          }}
          rows={rows}
          totalAPayer={totalAPayer || facture?.montant_ttc || 0}
        />
      </div>

      <div className="no-print mx-auto mt-8 max-w-[210mm] rounded-2xl p-6 text-center text-white" style={{ background: primary }}>
        <h3 className="mb-2 text-lg font-bold">Prêt à vous inscrire officiellement ?</h3>
        <p className="mb-4 text-sm text-white/85">
          Créez votre compte et soumettez votre dossier pour confirmer votre préinscription.
        </p>
        <Link
          to="/inscription"
          className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-2.5 text-sm font-bold text-slate-900 hover:bg-slate-100"
        >
          Créer mon compte →
        </Link>
      </div>
    </div>
  )
}
